export const COUNTRIES = [
  { code: 'MEX', name: 'México', count: 20 },
  { code: 'CAN', name: 'Canadá', count: 20 },
  { code: 'USA', name: 'Estados Unidos', count: 20 },
  { code: 'BRA', name: 'Brasil', count: 20 },
  { code: 'ARG', name: 'Argentina', count: 20 },
  { code: 'URY', name: 'Uruguai', count: 20 },
  { code: 'PAR', name: 'Paraguai', count: 20 },
  { code: 'CHI', name: 'Chile', count: 20 },
  { code: 'COL', name: 'Colômbia', count: 20 },
  { code: 'ECU', name: 'Equador', count: 20 },
  { code: 'PER', name: 'Peru', count: 20 },
  { code: 'VEN', name: 'Venezuela', count: 20 },
  { code: 'BOL', name: 'Bolívia', count: 20 },
  { code: 'ENG', name: 'Inglaterra', count: 20 },
  { code: 'SCO', name: 'Escócia', count: 20 },
  { code: 'WAL', name: 'País de Gales', count: 20 },
  { code: 'FRA', name: 'França', count: 20 },
  { code: 'GER', name: 'Alemanha', count: 20 },
  { code: 'ESP', name: 'Espanha', count: 20 },
  { code: 'POR', name: 'Portugal', count: 20 },
  { code: 'ITA', name: 'Itália', count: 20 },
  { code: 'NED', name: 'Holanda', count: 20 },
  { code: 'BEL', name: 'Bélgica', count: 20 },
  { code: 'CRO', name: 'Croácia', count: 20 },
  { code: 'SWE', name: 'Suécia', count: 20 },
  { code: 'DEN', name: 'Dinamarca', count: 20 },
  { code: 'NOR', name: 'Noruega', count: 20 },
  { code: 'POL', name: 'Polônia', count: 20 },
  { code: 'UKR', name: 'Ucrânia', count: 20 },
  { code: 'ROU', name: 'Romênia', count: 20 },
  { code: 'HUN', name: 'Hungria', count: 20 },
  { code: 'CZE', name: 'República Checa', count: 20 },
  { code: 'SVK', name: 'Eslováquia', count: 20 },
  { code: 'SVN', name: 'Eslovênia', count: 20 },
  { code: 'GRE', name: 'Grécia', count: 20 },
  { code: 'TUR', name: 'Turquia', count: 20 },
  { code: 'SRB', name: 'Sérvia', count: 20 },
  { code: 'BIH', name: 'Bósnia e Herzegovina', count: 20 },
  { code: 'ALB', name: 'Albânia', count: 20 },
  { code: 'MKD', name: 'Macedônia do Norte', count: 20 },
  { code: 'GEO', name: 'Geórgia', count: 20 },
  { code: 'AZE', name: 'Azerbaijão', count: 20 },
  { code: 'EGY', name: 'Egito', count: 20 },
  { code: 'MAR', name: 'Marrocos', count: 20 },
  { code: 'SEN', name: 'Senegal', count: 20 },
  { code: 'CMR', name: 'Camarões', count: 20 },
  { code: 'GHA', name: 'Gana', count: 20 },
  { code: 'JPN', name: 'Japão', count: 20 },
  { code: 'AUS', name: 'Austrália', count: 20 },
];

export const USERS = ['chris', 'isa', 'andre'];
